title: Sung Min Yoon
description: Sung Min's Personal Website
author: Sung Min Yoon
email: sy375@cornell.edu
phone: 
github: https://github.com/sy375
about: 
disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/KakaoTalk_20210925_083004790.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: 
    #- icon: fa-twitter
    #  link: 
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sy375/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/sy375"

#share:
#  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
#    - text: XML Feed
#      url: /feed.xml
# url: "http://localhost:4000"
url: "https://sy375.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
